export const PIXEL_CAT_SPRITE = [
  "......XXX....XXX......",
  "......XIXX..XXIX......",
  "......XIPX..XPIX......",
  ".....XXPPXXXXPPXX.....",
  "....XXPPPPSSPPPPXX....",
  "....XPPPPWWWWPPPPX....",
  "...XXPPWWWWWWWWPPXX...",
  "...XPPWWWWWWWWWWPPX...",
  "...XPWWEWWWWWWEWWPX..XX",
  "...XWWWBXWXWXBWWWWX.XTX",
  "...XWWWWXXXXXWWWWWXXTX.",
  "....XWWWWWWWWWWWWX.XTX",
  "....XXWWWWWWWWWWXXXXTTX",
  "...XXSWWWWWWWWWWWSSXXTX",
  "...XSSWWWWWWWWWWWSSXXTX",
  "...XSSWWWWWWWWWWWSSXXTX",
  "...XXXXXXWWWWWWXXXXXTX..",
  ".....XSSXWWWWXSSXXTTX.",
  ".....XSSXXXXXXSSXXXX..",
  ".....XXXX....XXXX.....",
] as const;

export const PIXEL_CAT_PALETTE_MAP: Record<string, string> = {
  X: "var(--cat-outline)",
  P: "var(--cat-fur-primary)",
  S: "var(--cat-fur-secondary)",
  T: "var(--cat-tail)",
  W: "var(--cat-fur-light)",
  I: "var(--cat-inner-ear)",
  E: "var(--cat-eyes)",
  B: "var(--cat-blush)",
};
